services:
  postgres:
    image: postgres:15-alpine
    container_name: deliveryinfra-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-delivery}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-delivery}
      POSTGRES_DB: ${POSTGRES_DB:-delivery}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  postgres-data: